spring:
  application:
    name: pd-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pd_ai_code_mother
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      database: 0
  session:
    store-type: redis
    timeout: 2592000
  profiles:
    active: local
  # 文件上传
  servlet:
    max-file-size: 10MB
    max-request-size: 10MB
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        # 30天过期
        max-age: 2592000
logging:
  level:
    com.pd.pdaicodemother: DEBUG
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.pd.pdaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# minio
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minio
  secretKey: minio123456



